### ISSUE TITLE
node is not attached to fixture when mounting as string

### ISSUE THREAD

**Issue by Hotell** [treshugart/bore#11]
If we wanna test attribute propagation to props via string like this
```
mount(
 `<bl-tooltip lable="Im so bored"></bl-tooltip>`
).wait(/*...*/)
```

it throws error.

This is caused by programatic error here
https://github.com/treshugart/bore/blob/master/src/index.js#L84

which should be 
```diff
-fixture.appendChild(node); // node is undefined
+fixture.appendChild(this.node);
```

**Comment by devopsmariocom** [comment]
We have with @Hotell actually discovered that this doesn't work either. Because if you try to [appendChild](https://github.com/treshugart/bore/blob/master/src/index.js#L84) firstChild of div created in `nodeFromHtml()` custom element doesn't work with polyfill on Firefox.

I guess that we could simply do `fixture.innerHTML = node;` instead of `fixture.appendChild(node);` here
https://github.com/treshugart/bore/blob/master/src/index.js#L84 for string input which could solve the issue.

**Comment by hopkins-tk** [comment]
We took a look at it & fixed the polyfills issue with @elmariofredo as well in #12.
