### ISSUE TITLE
add attributes support to bore.h

### ISSUE THREAD

**Issue by devopsmariocom** [treshugart/bore#14]
We would like to test setting attributes not just properties and for that we can simply implement attributes option same way as described here https://github.com/skatejs/dom-diff#attributes

**Comment by devopsmariocom** [comment]
it's actually already working as hBore is setting DOM attributes property :)

**Comment by Hotell** [comment]
it's not ;) :D

because various DOM reasons.

you can do this 
```js
mount(<my-elemenent attributes={{id:123,role:'woot'}})/>).wait() 
```

but it wont do what you think it might, because how DOM works. `attributes` work one way not two way. 
So although it will set your map to attributes, it wont reflect that to DOM, because `attributes` uses `NamedNodeMap` which is ArrayLike object with `Attr` instances....

So the right solution should be make `mount` aware about setting `attributes` via "normalized" way
